# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 20m
  tests: true
  skip-dirs-use-default: true
  skip-files:
    - bindings/gen_taiko_l1.go
    - bindings/gen_taiko_l2.go

issues:
  exclude-rules:
    - path: bindings/encoding/custom_error.go
      linters:
        - errorlint

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    - staticcheck
    - lll
    - bidichk
    - durationcheck
    - exportloopref
    - whitespace
    - errname
    - errorlint
    - errcheck
    - errchkjson
    - exhaustive
    - makezero

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 6
